version: "3.8"
services:

  front:
    depends_on:
      - api
    build: 
      context: ./front
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
        - JWT_SECRET=$JWT_SECRET
    env_file: .env
    environment:
      - PORT=3000
    ports:
      - 3000:3000

  api:
    depends_on:
      - postgres
      - redis
    build: ./api
    env_file: .env
    ports:
      - 4000:4000
    
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - chat_postgres_data:/var/lib/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - chat_redis_data:/var/lib/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - front
      - api

volumes:
  chat_postgres_data:
  chat_redis_data:
    