version: "3.8"
name: online-chat
services:
  front:
    depends_on:
      - api
    build: 
      context: ./front
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
        - JWT_SECRET=$JWT_SECRET
    env_file: .env
    environment:
      - PORT=3000
    ports:
      - 3000:3000

  api:
    depends_on:
      - postgres
      - redis
      - migrations
    build: 
      context: ./api
      target: production
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 4000:4000
    
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/data

  migrations:
    build: 
      context: ./api
      target: migration
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file: .env

  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - front
      - api
    ports:
      - "80:80"

volumes:
  postgres_data:
  redis_data:
